import { createCalendarEvent, refreshAccessToken } from "@/lib/googleAuth";
import { adminDb } from "@/lib/firebaseAdmin";
import { logRouteError } from "@/lib/errorLogger";

/**
 * POST /api/webhooks/calendar-sync
 * Webhook that receives an array of scheduled tasks from an AI agent's management plan
 * and automatically injects them into Google Calendar.
 * Body: { planId: string, tasks: [{ title, start, end, description }] }
 */
export async function POST(request) {
  try {
    const { planId, tasks } = await request.json();

    if (!planId || !tasks || !Array.isArray(tasks)) {
      return Response.json({ error: "planId and tasks array are required" }, { status: 400 });
    }

    const sysRef = adminDb.collection("system").doc("automation_status");
    const sysDoc = await sysRef.get();
    if (sysDoc.exists && sysDoc.data().killswitchEngaged) {
      return Response.json({ error: "Automation killswitch is engaged. Cannot sync to calendar." }, { status: 403 });
    }

    const tokensDoc = await adminDb.collection("settings").doc("google_oauth").get();
    if (!tokensDoc.exists) {
      return Response.json({ error: "Not connected to Google Workspace" }, { status: 401 });
    }

    const tokens = tokensDoc.data();
    let accessToken = tokens.accessToken;

    if (Date.now() > tokens.expiresAt) {
      try {
        const refreshed = await refreshAccessToken(tokens.refreshToken);
        accessToken = refreshed.access_token;
        await adminDb.collection("settings").doc("google_oauth").update({
          accessToken: refreshed.access_token,
          expiresAt: Date.now() + (refreshed.expires_in * 1000),
        });
      } catch {
        return Response.json({ error: "Token refresh failed" }, { status: 401 });
      }
    }

    const syncedEvents = [];

    // Push each task to Calendar
    for (const task of tasks) {
      if (!task.title || !task.start || !task.end) continue;
      
      const event = {
        summary: `[🤖 Plan: ${planId}] ${task.title}`,
        start: task.start.includes("T") ? { dateTime: task.start } : { date: task.start },
        end: task.end.includes("T") ? { dateTime: task.end } : { date: task.end },
        description: task.description || `Generated by Antigravity Hub Agent from plan: ${planId}`
      };

      try {
        const created = await createCalendarEvent(accessToken, "primary", event);
        syncedEvents.push(created.htmlLink);
      } catch (err) {
        console.warn(`Failed to sync task ${task.title}:`, err.message);
      }
    }

    // Update Plan Status in Firestore
    await adminDb.collection("management_plans").doc(planId).set({
      calendar_synced: true,
      syncedAt: new Date().toISOString(),
      calendarLinks: syncedEvents
    }, { merge: true });

    return Response.json({
      success: true,
      syncedCount: syncedEvents.length,
      links: syncedEvents
    });

  } catch (error) {
    console.error("[/api/webhooks/calendar-sync]", error);
    logRouteError("automation", "/api/webhooks/calendar-sync error", error, "/api/webhooks/calendar-sync");
    return Response.json({ error: error.message }, { status: 500 });
  }
}
